config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  resources :posts
  resources :rssfeeds
  root 'posts#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  post '/send_tweet', to: 'posts#send_tweet'
  post '/send_vk', to: 'posts#send_vk'
  get  '/get_vk_token', to: 'accounts#get_vk_token'
  post '/send_fb', to: 'posts#send_fb'
  get '/:page', to: 'pages#show'
  match '/rssfeeds/:id' => 'rssfeeds#rss', via: [:get, :post], :as => :rss
end

app/views/shared/_accounts.html.erb
<h3>
  <%= link_to 'Accounts', accounts_path %>
</h3>

<table>

  <% Account.where(user_id: current_user.id).each_with_index do |account, index| %>

  <tr>
    <td><%= index.to_i + 1 %></td>
    <td>
      <%= account.provider %>
      <%= account.email %>
    </td>
  </tr>

  <% end %>

</table>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= link_to 'Postinger', root_path, class: 'navbar-brand' %>

   <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
 
      <% if user_signed_in? %>

      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%#= render plain: "User id #{current_user.id.to_s}", class: 'nav-link'  %>
      </li>

      <% else %>
     
      <li class="nav-item">
        <%= link_to 'Sign Up',  new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
      </li>

      <% end %>

     <li class="nav-item">
        <%= link_to 'About', '/about', class: 'nav-link' %>
      </li>
  
    </ul>
  </div>
</nav>

app/views/shared/_rssfeeds.html.erb
<h3>
  <%= link_to 'RSS feeds', rssfeeds_path %>
</h3>

<table>

  <% Rssfeed.where(user_id: current_user.id).each do |rss| %>

  <tr>
    <td>
      <%= rss.title %>
    </td>
  </tr>

  <% end %>

</table>