config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  resources :posts
  resources :rssfeeds
  root 'posts#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  post '/send_tweet', to: 'posts#send_tweet'
  post '/send_vk', to: 'posts#send_vk'
  get  '/get_vk_token', to: 'accounts#get_vk_token'
  post '/send_fb', to: 'posts#send_fb'
  get '/:page', to: 'pages#show'
  match '/rssfeeds/:id' => 'rssfeeds#rss', via: [:get, :post], :as => :rss
end

app/models/rssfeed.rb
class Rssfeed < ApplicationRecord
  belongs_to :user
end

app/controllers/rssfeeds_controller.rb
class RssfeedsController < ApplicationController
  before_action :set_rssfeed, only: [:show, :edit, :update, :destroy, :rss]

  def index
    @rssfeeds = Rssfeed.where(user_id: [current_user.id])
  end

  def show;end

  def new
    @rssfeed = Rssfeed.new
  end

  def edit;end

  def create
    @rssfeed = Rssfeed.new(rssfeed_params)
    @rssfeed.user_id = current_user.id
    if @rssfeed.save
      redirect_to rssfeeds_path, notice: 'RSS was successfully created.'
    else
      render :new
    end
  end

  def update
    if @rssfeed.update(rssfeed_params)
      redirect_to rssfeeds_path, notice: 'RSS was successfully updated.' 
    else
      render :edit, notice: 'RSS was successfully updated.'  
    end
  end

  def destroy
    @rssfeed.destroy
    redirect_to root_path, notice: 'RSS was successfully destroyed.'
  end

  def rss
    feeds = Feedjira::Feed.fetch_and_parse(@rssfeed.url)
    feeds.entries.each do |feed|
      @post = Post.new(user_id: current_user.id, title: feed.title, body: feed.summary)
      @post.save
    end
    redirect_to rssfeed_path, notice: 'Posts were successfully created.'
  end

  private

  def set_rssfeed
    @rssfeed = Rssfeed.find(params[:id])
  end

  def rssfeed_params
    params.require(:rssfeed).permit(:title, :url, :user_id)
  end
end

app/helpers/rssfeeds_helper.rb
module RssfeedsHelper
end

app/views/rssfeeds/_form.html.erb
<%= simple_form_for(@rssfeed) do |f| %>
  <%= f.error_notification %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rssfeeds/edit.html.erb
<h1>Editing RSS</h1>

<%= render 'form', rssfeed: @rssfeed %>

<%= link_to 'Back', root_path %>

app/views/rssfeeds/index.html.erb
<h1>RSS feeds</h1>

<table>

  <% @rssfeeds.each do |rss| %>

  <tr>
    <td><%= rss.title %></td>
    <td><%= rss.url %></td>
    <td><%= link_to 'Show', rss %></td>
    <td><%= link_to 'Edit', edit_rssfeed_path(rss) %></td>
    <td><%= link_to 'Destroy', rss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

    <% end %>

</table>

<%= link_to 'Add RSS feed', new_rssfeed_path %><br />
<%= link_to 'Back', root_path %><br />

app/views/rssfeeds/new.html.erb
<h1>New RSS feed</h1>

<%= render 'form', rssfeed: @rssfeed %>

<%= link_to 'Back', root_path %>

app/views/rssfeeds/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @rssfeed.title %>
</p>

<p>
  <strong>RSS url:</strong>
  <%= @rssfeed.url %>
</p>

<%= link_to 'Edit', edit_rssfeed_path(@rssfeed) %><br />
<%= link_to 'Back', rssfeeds_path %><br />

<%= form_for :url, url: rss_path, method: :post do |f| %>
  <%= f.hidden_field :url, { value: @rssfeed.url }%>
  <%= f.submit "Get RSS" %>
<% end %>