config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  resources :posts
  resources :rssfeeds
  root 'posts#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  post '/send_tweet', to: 'posts#send_tweet'
  post '/send_vk', to: 'posts#send_vk'
  get  '/get_vk_token', to: 'accounts#get_vk_token'
  post '/send_fb', to: 'posts#send_fb'
  get '/:page', to: 'pages#show'
  match '/rssfeeds/:id' => 'rssfeeds#rss', via: [:get, :post], :as => :rss
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image
  # validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.where(user_id: [current_user.id])
  end

  def show;end

  def new
    @post = Post.new
  end

  def edit;end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def send_tweet
    current_user.twitter.update(message[0...140])
    redirect_to :back, notice: 'Post was seccussefully send to twitter'
  end

  def message
    params[:body].inspect.to_s.gsub!(/<[a-zA-Z\/][^>]*>/,"").to_s
  end

  def send_vk
    current_user.vk.wall.post(message: message)
    redirect_to :back, notice: 'Post was seccussefully send to vk'
  end

  def send_fb
    current_user.facebook.put_wall_post(message)
    redirect_to :back, notice: 'Post was seccussefully send to Facebook'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for post, html: { multipart: true } do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.trix_editor :body %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= raw post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Post', new_post_path %>

<div>
  <%#= render 'shared/accounts' %>
  <%#= render 'shared/rssfeeds' %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= raw @post.body %>
</p>

<p>
  <%= image_tag @post.image.url %>
</p>

<p>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<% accounts = Account.where(user_id: [current_user.id]).select(:provider).each do |q| %>
  <% if q.provider == 'twitter' %>
    <%= form_for :body, url: send_tweet_path, method: :post do |f| %>
      <%= f.hidden_field :body, { value: @post.body }%>
      <%= f.submit "Send Tweet" %>
    <% end %>
  <% elsif q.provider == 'vkontakte' %>
    <%= form_for :body, url: send_vk_path, method: :post do |f| %>
      <%= f.hidden_field :body, { value: @post.body }%>
      <%= f.submit "Send to VK" %>
    <% end %>
  <% elsif q.provider == 'google_oauth2' %>
    <%= form_for :body, url: send_vk_path, method: :post do |f| %>
      <%= f.hidden_field :body, { value: @post.body }%>
      <%= f.submit "Send to Google+" %>
    <% end %>
  <% elsif q.provider == 'facebook' %>
    <%= form_for :body, url: send_fb_path, method: :post do |f| %>
      <%= f.hidden_field :body, { value: @post.body }%>
      <%= f.submit "Send to Facebook" %>
    <% end %>
  <% end %>
<% end %>