config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  resources :posts
  resources :rssfeeds
  root 'posts#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  post '/send_tweet', to: 'posts#send_tweet'
  post '/send_vk', to: 'posts#send_vk'
  get  '/get_vk_token', to: 'accounts#get_vk_token'
  post '/send_fb', to: 'posts#send_fb'
  get '/:page', to: 'pages#show'
  match '/rssfeeds/:id' => 'rssfeeds#rss', via: [:get, :post], :as => :rss
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  def self.find_for_oauth(auth)
    if ['twitter'].include?(auth.provider)
      find_or_create_by(
        uid: auth.uid,
        provider: auth.provider,
        email: auth.info.email,
        token_tw: auth.credentials.token,
        secret_tw: auth.credentials.secret
      )
    elsif ['facebook'].include?(auth.provider)
      find_or_create_by(
        uid: auth.uid,
        provider: auth.provider,
        email: auth.info.email,
        token_fb: auth.credentials.token
      )
    elsif ['google_oauth2'].include?(auth.provider)
      find_or_create_by(
        uid: auth.uid,
        provider: auth.provider,
        email: auth.info.email,
        token_g: auth.credentials.token
      )
    elsif ['vkontakte'].include?(auth.provider)
      find_or_create_by(
        uid: auth.uid,
        provider: auth.provider,
        email: auth.info.email
      )
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = Account.where(user_id: current_user.id)
  end

  def show;end

  def new
    @account = Account.new
  end

  def edit; end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_url, notice: 'Account was successfully destroyed.'
  end

  def get_vk_token
    vk_url = 'https://oauth.vk.com/authorize?client_id=5963835&scope=groups,wall,offline,photos&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token'
    redirect_to vk_url
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:account, :user_id, :email, :provider, :token_vk)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  <div>
    <%= f.label :uid %>
    <%= f.text_field :uid %>
  </div>

  <div>
    <%= f.label :provider %>
    <%= f.text_field :provider %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email, size: 40 %>
  </div>

  <% if @account.provider == 'vkontakte'%>
    <div>
      <%= f.label :token_vk %>
      <%= f.text_field :token_vk, size: 110 %>
    </div>
  <% elsif @account.provider == 'twitter' %>
    <div>
      <%= f.label :token_tw %>
      <%= f.text_field :token_tw, size: 110 %>
    </div>
    <div>
      <%= f.label :secret_tw %>
      <%= f.text_field :secret_tw, size: 110 %>
    </div>
    <% elsif @account.provider == 'facebook' %>
      <%= %>
  <% end %>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', account_path %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>

  <%= link_to 'Add twitter account', '/users/auth/twitter' %><br />
  <%= link_to 'Add fb account', '/users/auth/facebook' %><br />
  <%= link_to 'Add VK account', '/users/auth/vkontakte' %><br />


<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.provider %></td>
        <td><%= account.email %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Account', new_account_path %><br />
<%= link_to 'Back', root_path %><br />

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p>
  <strong>uid:</strong>
  <%= @account.uid %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @account.provider %>
</p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>
 
<% if @account.provider == 'vkontakte' %>
  <p>
    <strong>Token VK:</strong>
    <%= @account.token_vk %>
  </p>
  <% elsif @account.provider == 'twitter' %>
  <p>
    <strong>Twitter key:</strong>
    <%= @account.token_tw %>
  </p>
  <p>
    <strong>Twitter secret:</strong>
    <%= @account.secret_tw %>
  </p>
  <% elsif @account.provider == 'facebook' %>
  <% %> 
<% end %>

<% if @account.provider == 'vkontakte' %>  

  <p> Для публикаций на стену пользователя необходимо получить токен с соответствующими правами доступа. Для 
  его получения нажмите на кнопку "Get VK token". После этого вы будете перенапрввлены на страницу входа vk. Дайте  
  приложению запрашиваемые права. Скопируйте с адресной строки браузера значение пареметра access_token. Откройте 
  аккаунт для редактирования и добавьте в поле "Token VK" скопированый токен.</p>

<% end %>

<p>
<%= link_to 'Get VK token', '/get_vk_token' %> 
</p>
<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>